### ISSUE TITLE
Null Safety?

### ISSUE THREAD

**Issue by FRANIAZA** [DevOrbiter/drag_and_drop_gridview#17]
I read #15, so does this package support null safety now?

**Comment by larssn** [comment]
The repo does. There needs to be uploaded a new release to pub.dev.

**Comment by ChristianKleineidam** [comment]
@DevOrbiter can you upload the new version to pub.dev?

**Comment by pawelpetruch** [comment]
@DevOrbiter can you look into that?

**Comment by pawelpetruch** [comment]
It can still be used this way in pubspec.yaml
```
drag_and_drop_gridview:
    git: 
      url: https://github.com/DevOrbiter/drag_and_drop_gridview.git
      ref: master
```
